{% set name = "floatcsep" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/floatcsep-{{ version }}.tar.gz
  sha256: d5f66d911c6aadc70402af7c73d8502e16cf5bdb6804828b7ea6c11bfcef4fde

build:
  entry_points:
    - floatcsep = floatcsep.cmd.main:floatcsep
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=52.0
    - wheel
    - pip
  run:
    - python >=3.8
    - git
    - numpy
    - dateparser
    - docker-py
    - flake8
    - gitpython
    - h5py
    - matplotlib-base
    - pycsep
    - pyshp
    - pyyaml
    - requests
    - seaborn
    - pytables
    - xmltodict

test:
  imports:
    - floatcsep
  commands:
    - pip check
    - floatcsep --help
  requires:
    - pip

about:
  home: https://github.com/cseptesting/floatcsep.git
  summary: CSEP Floating Experiment application
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pciturri
